package com.onlinecash.loanswithout;

import android.content.Context;
import android.graphics.Typeface;
import android.text.Html;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.TextView;

import androidx.annotation.NonNull;
import androidx.recyclerview.widget.RecyclerView;

import java.util.ArrayList;
import java.util.HashMap;

public class UserAgreementAdapter extends RecyclerView.Adapter<UserAgreementAdapter.TextHolder> {
    private final Context context;

    private final ArrayList<HashMap<String, Integer>> textParagraphs;

    public UserAgreementAdapter(Context context) {
        this.context = context;

        textParagraphs = new ArrayList<>();
        HashMap<String, Integer> textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_1), Typeface.NORMAL);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_2), Typeface.ITALIC);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_3), Typeface.NORMAL);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_4), Typeface.ITALIC);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put("<font color=\"#0066BF\">" + context.getString(R.string.ua_paragraph_5) + "</font>", Typeface.BOLD);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_6), Typeface.BOLD);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_7), Typeface.NORMAL);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_8), Typeface.ITALIC);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_9), Typeface.BOLD);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_10), Typeface.NORMAL);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_11), Typeface.ITALIC);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_12), Typeface.BOLD);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_13), Typeface.NORMAL);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_14), Typeface.ITALIC);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_15), Typeface.BOLD);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_16), Typeface.NORMAL);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_17), Typeface.ITALIC);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put("<font color=\"#0066BF\">" + context.getString(R.string.ua_paragraph_18) + "</font>", Typeface.BOLD);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_19), Typeface.NORMAL);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_20), Typeface.ITALIC);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put("<font color=\"#0066BF\">" + context.getString(R.string.ua_paragraph_21) + "</font>", Typeface.BOLD);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put("<font color=\"#0066BF\">" + context.getString(R.string.ua_paragraph_22) + "</font>", Typeface.BOLD_ITALIC);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_23), Typeface.NORMAL);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_24), Typeface.NORMAL);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_25), Typeface.NORMAL);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_26), Typeface.NORMAL);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_27), Typeface.NORMAL);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_28), Typeface.NORMAL);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_29), Typeface.ITALIC);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_30), Typeface.ITALIC);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_31), Typeface.ITALIC);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_32), Typeface.ITALIC);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_33), Typeface.ITALIC);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_34), Typeface.ITALIC);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put("<font color=\"#0066BF\">" + context.getString(R.string.ua_paragraph_35) + "</font>", Typeface.BOLD_ITALIC);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_36), Typeface.NORMAL);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_37), Typeface.ITALIC);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraphs.add(textParagraph);
        textParagraph.put("<font color=\"#0066BF\">" + context.getString(R.string.ua_paragraph_38) + "</font>", Typeface.BOLD_ITALIC);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_39), Typeface.NORMAL);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_40), Typeface.ITALIC);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_41), Typeface.NORMAL);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_42), Typeface.ITALIC);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_43), Typeface.NORMAL);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_44), Typeface.ITALIC);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_45), Typeface.NORMAL);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_460), Typeface.BOLD);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_461), Typeface.NORMAL);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_470), Typeface.BOLD);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_471), Typeface.NORMAL);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_480), Typeface.BOLD);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_481), Typeface.NORMAL);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_49), Typeface.ITALIC);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_500), Typeface.BOLD_ITALIC);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_501), Typeface.ITALIC);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_510), Typeface.BOLD_ITALIC);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_511), Typeface.ITALIC);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_520), Typeface.BOLD_ITALIC);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_521), Typeface.ITALIC);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put("<font color=\"#0066BF\">" + context.getString(R.string.ua_paragraph_53) + "</font>", Typeface.BOLD);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_54), Typeface.BOLD);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_55), Typeface.NORMAL);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_56), Typeface.NORMAL);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_57), Typeface.NORMAL);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_58), Typeface.NORMAL);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_59), Typeface.NORMAL);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_60), Typeface.NORMAL);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_61), Typeface.NORMAL);
        textParagraphs.add(textParagraph);
        textParagraph.put(context.getString(R.string.ua_paragraph_62), Typeface.NORMAL);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_63), Typeface.NORMAL);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_64), Typeface.NORMAL);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_65), Typeface.NORMAL);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_66), Typeface.NORMAL);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_67), Typeface.NORMAL);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_68), Typeface.NORMAL);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_69), Typeface.NORMAL);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put("<font color=\"#0066BF\">" + context.getString(R.string.ua_paragraph_70) + "</font>", Typeface.BOLD);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_71), Typeface.NORMAL);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_72), Typeface.ITALIC);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_73), Typeface.NORMAL);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_74), Typeface.ITALIC);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_75), Typeface.NORMAL);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_76), Typeface.ITALIC);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put("<font color=\"#0066BF\">" + context.getString(R.string.ua_paragraph_77) + "</font>", Typeface.BOLD);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put("<font color=\"#0066BF\">" + context.getString(R.string.ua_paragraph_78) + "</font>", Typeface.BOLD);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_79), Typeface.NORMAL);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_80), Typeface.NORMAL);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_81), Typeface.NORMAL);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_82), Typeface.NORMAL);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_83), Typeface.NORMAL);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_84), Typeface.NORMAL);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_85), Typeface.ITALIC);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_86), Typeface.ITALIC);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_87), Typeface.ITALIC);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_88), Typeface.ITALIC);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_89), Typeface.ITALIC);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_90), Typeface.ITALIC);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put("<font color=\"#0066BF\">" + context.getString(R.string.ua_paragraph_91) + "</font>", Typeface.BOLD);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_92), Typeface.NORMAL);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_93), Typeface.ITALIC);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put("<font color=\"#0066BF\">" + context.getString(R.string.ua_paragraph_94) + "</font>", Typeface.BOLD);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_95), Typeface.NORMAL);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_96), Typeface.ITALIC);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put("<font color=\"#0066BF\">" + context.getString(R.string.ua_paragraph_97) + "</font>", Typeface.BOLD);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_98), Typeface.NORMAL);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_99), Typeface.ITALIC);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_100), Typeface.NORMAL);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_101), Typeface.NORMAL);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_102), Typeface.NORMAL);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put("<font color=\"#0066BF\">" + context.getString(R.string.ua_paragraph_103) + "</font>", Typeface.BOLD);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_104), Typeface.NORMAL);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_105), Typeface.ITALIC);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put("<font color=\"#0066BF\">" + context.getString(R.string.ua_paragraph_106) + "</font>", Typeface.BOLD);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_107), Typeface.NORMAL);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_108), Typeface.ITALIC);
        textParagraphs.add(textParagraph);
        textParagraph.put("<font color=\"#0066BF\">" + context.getString(R.string.ua_paragraph_109) + "</font>", Typeface.BOLD);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_110), Typeface.NORMAL);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_111), Typeface.ITALIC);
        textParagraphs.add(textParagraph);
        textParagraph.put("<font color=\"#0066BF\">" + context.getString(R.string.ua_paragraph_112) + "</font>", Typeface.BOLD);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_113), Typeface.NORMAL);
        textParagraphs.add(textParagraph);
        textParagraph = new HashMap<>();
        textParagraph.put(context.getString(R.string.ua_paragraph_114), Typeface.ITALIC);
        textParagraphs.add(textParagraph);
    }


    @NonNull
    @Override
    public TextHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
        View v = LayoutInflater.from(context).inflate(R.layout.text, parent, false);

        return new TextHolder(v);
    }

    @Override
    public void onBindViewHolder(@NonNull final TextHolder holder, int position) {
        holder.text.setText((CharSequence) textParagraphs.get(position).keySet().toArray()[0]);
        holder.text.setTypeface(null, (Integer) textParagraphs.get(position).values().toArray()[0]);
        holder.text.setText(Html.fromHtml(String.valueOf(textParagraphs.get(position).keySet().toArray()[0])));
    }

    @Override
    public int getItemCount() {
        return textParagraphs.size();
    }

    static class TextHolder extends RecyclerView.ViewHolder {
        TextView text;

        public TextHolder(@NonNull View itemView) {
            super(itemView);
            text = itemView.findViewById(R.id.userAgreementTextView);
        }
    }
}
